---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: broker
    run_list:
      - recipe[confluent::kafka_broker]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      confluent:
        kafka:
          broker_id: 1
  - name: zookeeper
    run_list:
      - recipe[confluent::zookeeper]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      confluent:
        zookeeper:
          my_id: 1
  - name: schema-registry
    run_list:
      - recipe[confluent::schema_registry]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      confluent:
        schema_registry:
          kafkastore_connection_url: localhost:2181